### ISSUE TITLE
tag a new release

### ISSUE THREAD

**Issue by pietroppeter** [subsetpark/ad#1]
running `nimble install ad` fails to build with Nim 1.6.0.

nimble then asks to try install `ad@#head` which succeeds.

Tagging a new release should solve this.

_off topic:_

This lovely (!) [HN thread](https://news.ycombinator.com/item?id=30354391) about the recent death of dc's author prompted me to install this (I did not know all the history about dc, it is great!) and since I have the occasion I want to compliment on your past work in Nim and your current blog.
In particular, I find that both [your video at PyGotham](https://pyvideo.org/pygotham-2017/nim-a-new-option-for-optimizing-inner-loops.html) and your blogpost on [Nim for Python programmers](https://blog.zdsmith.com/posts/nim-for-python-programmers.html)  are excellent and still very fresh and true today.

**Comment by subsetpark** [comment]
Thank you for the very kind note! I tagged a new release and then `nimble install ad` built and installed it without a problem.

**Comment by pietroppeter** [comment]
tested also on my side. all good!
